name: citeworth
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=10.2.89
  - jsonlines=1.2.0
  - matplotlib=3.2.2
  - numpy=1.18.5
  - pandas=1.0.5
  - pip=20.1.1
  - python=3.8.3
  - pytorch=1.6.0
  - scikit-learn=0.23.1
  - scipy=1.5.0
  - seaborn=0.10.1
  - spacy=2.3.2
  - pip:
    - bpemb==0.3.2
    - ipdb==0.13.3
    - ipython==7.18.1
    - nltk==3.5
    - pytokenizations==0.7.2
    - pytorch-crf==0.7.2
    - rouge-score==0.0.4
    - scispacy==0.2.5
    - tqdm==4.46.1
    - transformers==4.2.1
    - wandb==0.9.7

